### ISSUE TITLE
Results not actually filtered

### ISSUE THREAD

**Issue by ivangreene** [aeyoll/soulseek-cli#1]
on lines 34 and 37 of index.js, `res.filter` is called, but not reassigned. According to MDN, `Array.prototype.filter` returns a copy and doesn't mutate the original array.

Btw, cool project and I'm very interested in a Soulseek CLI!

**Comment by aeyoll** [comment]
It's fixed in c5b5a439e9b98b95f212fd57b3e6243570e0161c.
Thanks for your interest in this CLI, this is highly experimental for the moment, but not missing too much to be functional. Don't hesitate to contribute! :)
