### ISSUE TITLE
i love you

### ISSUE THREAD

**Issue by ghost** [aeyoll/soulseek-cli#15]
very nice software thank you

**Comment by ghost** [comment]
could add more info for files description for results of search?  Is it possible to make the program non-interactive? So one command of soulseek-cli search song   to return in terminal and end program? Rather than it go into a "pick file" prompt. Seperate commands, search/download ?

**Comment by ghost** [comment]
Ok, managed to make it fit my use case better, but as a feature request: Could you add more information from the search results? Like bit-rate, song duration?

**Comment by aeyoll** [comment]
Hello, thanks for the love message! :smiley: 

I added some extra information in the latest release (0.0.17): average speed, folder size and bitrate. I don't have the info on song duration, so I can't display it.

For the non interactive version, I don't think it could work since the first result can be very far away from what you want to get. IMO, it needs human control.

**Comment by ghost** [comment]
Since the new version I'm unable to install. I tested across two different systems (my laptop and desktop) the errors are the same across both.

```
/usr/local/bin/soulseek -> /usr/local/lib/node_modules/soulseek-cli/cli.js                                                                                                                                           

> keytar@7.3.0 install /usr/local/lib/node_modules/soulseek-cli/node_modules/keytar
> prebuild-install || npm run build

prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 65534:1000 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}

> keytar@7.3.0 build /usr/local/lib/node_modules/soulseek-cli/node_modules/keytar
> node-gyp rebuild

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/14.15.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/soulseek-cli/node_modules/keytar/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/soulseek-cli/node_modules/keytar/.node-gyp'
gyp ERR! System Linux 5.10.14-200.fc33.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/soulseek-cli/node_modules/keytar
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@7.3.0 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@7.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! keytar@7.3.0 install: `prebuild-install || npm run build`
npm ERR! Exit status 243
npm ERR! 
npm ERR! Failed at the keytar@7.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-15T05_01_55_307Z-debug.log
```

relevant bits from the debug.logs
```
2841 silly install keytar@7.3.0
2842 info lifecycle keytar@7.3.0~install: keytar@7.3.0
2843 verbose lifecycle keytar@7.3.0~install: unsafe-perm in lifecycle false
2844 verbose lifecycle keytar@7.3.0~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/soulseek-cli/node_modules/keytar/node_modules/.bin:/usr/local/lib/node_modules/soulseek-cli/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin
2845 verbose lifecycle keytar@7.3.0~install: CWD: /usr/local/lib/node_modules/soulseek-cli/node_modules/keytar
2846 silly lifecycle keytar@7.3.0~install: Args: [ '-c', 'prebuild-install || npm run build' ]
2847 silly lifecycle keytar@7.3.0~install: Returned: code: 243  signal: null
2848 info lifecycle keytar@7.3.0~install: Failed to exec install script
```

I agree that in most cases you would want user control, but currently my goals are to have something that can automatically download spotify playlists via soulseek. Currently I have spotify playlists converted to a .txt with Artist - Title on each line, then shell script and your program to pass those lines into search queries and download the 1st result. But often the downloads would be in low bit-rate, now that bit-rate is specified in the search results I think I can have a good auto .flac downloader for large playlists. 

But if you could make instructions on how to compile from source I could try to add that natively in the program and merge. I have not developed node before but my pursuit of free music is a strong driver :P

**Comment by aeyoll** [comment]
> Since the new version I'm unable to install. I tested across two different systems (my laptop and desktop) the errors are the same across both.
> 
> ```
> /usr/local/bin/soulseek -> /usr/local/lib/node_modules/soulseek-cli/cli.js                                                                                                                                           
> 
> > keytar@7.3.0 install /usr/local/lib/node_modules/soulseek-cli/node_modules/keytar
> > prebuild-install || npm run build
> 
> prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
> npm ERR! code EACCES
> npm ERR! syscall scandir
> npm ERR! path /root/.npm/_logs
> ...

It looks like a permission issue on your side, are you trying to install soulseek-cli as root?

> I agree that in most cases you would want user control, but currently my goals are to have something that can automatically download spotify playlists via soulseek. Currently I have spotify playlists converted to a .txt with Artist - Title on each line, then shell script and your program to pass those lines into search queries and download the 1st result. But often the downloads would be in low bit-rate, now that bit-rate is specified in the search results I think I can have a good auto .flac downloader for large playlists.
> 
> But if you could make instructions on how to compile from source I could try to add that natively in the program and merge. I have not developed node before but my pursuit of free music is a strong driver :P

For now, soulseek-cli is filtering everything that is not a mp3, but I guess I could make a flac mode. Also, you could already filter by bitrate (`--quality=320` for example)

Please see [CONTRIBUTING.md](https://github.com/aeyoll/soulseek-cli/blob/develop/CONTRIBUTING.md) for instructions on how to develop your own features.

**Comment by aeyoll** [comment]
Update: I added a mode option to choose if you want mp3 or flac. Please see the updated README for more info (version 0.0.18 has been published)

**Comment by ghost** [comment]
In my experience the quality filter did not work (but from prev version), I had it set to 320 and would result with many 128 & 192 rips.

The errors I supplied earlier were ran under a root account. Thursday I will have time to troubleshoot. 
Again thank you for the very nice software, was pulling my hair out trying to get museek to work before I found this

**Comment by aeyoll** [comment]
> In my experience the quality filter did not work (but from prev version), I had it set to 320 and would result with many 128 & 192 rips.

Good catch, I just fixed the quality filter (available in the new version 0.0.19).
 
> The errors I supplied earlier were ran under a root account. Thursday I will have time to troubleshoot.
> Again thank you for the very nice software, was pulling my hair out trying to get museek to work before I found this

Thanks a lot!

**Comment by aeyoll** [comment]
Closing this issue for now, I'll be happy to review your PR once you'll add your feature. Thanks again!

**Comment by rnmp** [comment]
came here to also share the love
