### ISSUE TITLE
(node:32072) UnhandledPromiseRejectionWarning: Error: Cannot autolaunch D-Bus without X11 $DISPLAY

### ISSUE THREAD

**Issue by aloysiusantioch** [aeyoll/soulseek-cli#19]
# soulseek login
? Login username1
? Password [hidden]

(node:32072) UnhandledPromiseRejectionWarning: Error: Cannot autolaunch D-Bus without X11 $DISPLAY
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:32072) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aeyoll** [comment]
Hey @aloysiusantioch,
Thanks for reporting this bug. From what I have found, it's related to the underlaying lib to save the credential to the OS keystore (https://github.com/atom/node-keytar). This lib seems to need X11.

I found this related issue: https://github.com/atom/node-keytar/issues/224#issuecomment-540459884. They recommend to install xvfb. Can you give it a try please? Thanks a lot

**Comment by geoff-maddock** [comment]
I'm running into the same error.  I'm running in WSL Ubuntu 18.04.4 LTS.  Installed xvfb but still getting the same error:

```
soulseek login
? Login myusername
? Password [hidden]
node:internal/process/promises:225
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: Cannot autolaunch D-Bus without X11 $DISPLAY]
```

**Comment by aeyoll** [comment]
Hey @aloysiusantioch and @geoff-maddock, 
I added some instructions in the README to run soulseek-cli in a headless environment: https://github.com/aeyoll/soulseek-cli#on-headless-linux
Can you give it a try? Thanks!
