### ISSUE TITLE
After I attempt to login, I get the following error mesage:

### ISSUE THREAD

**Issue by WhereAreWeSeeing** [aeyoll/soulseek-cli#20]
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files]

This is probably the wrong place for this, I just wanted to ask if this an issue on my end. I couldn't find anything I believed to be relevant looking up this error message & I didn't see anything in the documentation on what to do in this situation.

**Comment by aeyoll** [comment]
Hello @sgreenden, what's your setup to reproduce this bug please?

**Comment by WhereAreWeSeeing** [comment]
My setup? I am on Arch Linux. There doesn't seem to be any potentially missing dependencies. I have the nodejs 15.14.0-1 package from the community repository. I did npm install -g soulseek-cli. The install went through successfully. I then did soulseek login and used the username and password from the same account I am logged into soulseekqt with, from which I then get that error message. I also tried using a new account name and an older account name.

**Comment by aeyoll** [comment]
Can you try to uninstall soulseek-cli, then install libsecret (`sudo pacman -S libsecret`), and finally reinstall soulseek-cli please? If it works, I'll update the README with instructions. Thanks!

**Comment by WhereAreWeSeeing** [comment]
I already had libsecret installed, I uninstalled soulseek-cli, then reinstalled libsecret and I had the same issue.

`node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files]`

**Comment by aeyoll** [comment]
I found this related issue: https://github.com/Foundry376/Mailspring/issues/681#issuecomment-497740495

It looks like `libsecret` relies on `gnome-keyring`. Can you try to install it? Even though it seems a bit odd it you don't use Gnome at all.

Some other people have issues with the login stored in the keyring, I think I need to consider an alternative method for authentication.

**Comment by WhereAreWeSeeing** [comment]
The login command worked after doing that, thank you.
