### ISSUE TITLE
Feature Request: List only files, not folders

### ISSUE THREAD

**Issue by ghost** [aeyoll/soulseek-cli#21]
Having a flag to add to only display files, rather than entire folders, would be very beneficial for scripting. Also, many times I just want to download *one* song, and the current setup requires me to download the entire folder, which is bad for bandwidth and also disk space.

Love the project btw <3 <3

**Comment by 0xGodspeed** [comment]
I would like this feature too please.
Also, thank you for making this. Using this on termux was the only way I could find to use soulseek on mobile.

**Comment by BachoSeven** [comment]
@godspeedfw in the last few months a new Android app was developed and it works amazingly, it's called Seeker https://github.com/jackBonadies/SeekerAndroid

**Comment by 0xGodspeed** [comment]
@BachoSeven thanks! I didn't know about that app
