### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by iynere** [aeyoll/soulseek-cli#28]
```
(node:21912) UnhandledPromiseRejectionWarning: Error: Cannot spawn a message bus without a machine-id: 
Unable to load /data/data/com.termux/files/usr/var/lib/dbus/machine-id or 
/data/data/com.termux/files/usr/etc/machine-id: Failed to open file 
“/data/data/com.termux/files/usr/var/lib/dbus/machine-id”: No such file or directory
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21912) UnhandledPromiseRejectionWarning: Unhandled promise rejection. 
This error originated either by throwing inside of an async function without a catch block, 
or by rejecting a promise which was not handled with .catch().
To terminate the node process on unhandled promise rejection, use the CLI flag 
`--unhandled-rejections=strict` 
(see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21912) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. 
In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Trying to use this on Android via Termux, which may be part of the problem. Even a pointer as to resolving this error message would help, and I can keep poking around.

**Comment by iynere** [comment]
Okay, for anyone else trying to figure this out—making progress... [Followed these instructions](https://wiki.termux.com/wiki/Graphical_Environment) to set up XServer (`pkg install x11-repo`, install XServer XSDL app, put `export DISPLAY=localhost:0` in `~/.bashrc`, run `pkg install fluxbox`)

Now, error message is as follows:

```
(node:3397) UnhandledPromiseRejectionWarning: 
Error: Error spawning command line 
“dbus-launch --autolaunch=e02e2a1269e14fc27830237f60cf8295 
--binary-syntax --close-stderr”: Child process exited with code 1
```

**Comment by iynere** [comment]
More progress, ran `dbus-launch` first and made sure XServer XSDL app was running, new error message is:

```
UnhandledPromiseRejectionWarning: Error: 
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: 
The name org.freedesktop.secrets was not provided by any .service files
```

**Comment by iynere** [comment]
Think I'm having [this problem](https://github.com/aeyoll/soulseek-cli/issues/20#issuecomment-816808392) now... Not sure how to install `gnome-keyring` in Termux...

**Comment by iynere** [comment]
From what I can tell, this is an issue with  the `keytar` NPM package and its dependencies...

**Comment by aeyoll** [comment]
Hello @iynere, thanks for reaching out!
A few people are indeed having trouble to setup soulseek-cli in a headless environment, and the guilty is node-keytar.

I found this post on how they are setting things up in their test environmnent: https://github.com/atom/node-keytar/issues/224#issuecomment-540459884

Can you give it a try? Thanks!

**Comment by aeyoll** [comment]
Hey @iynere 
I added some instructions in the README to run soulseek-cli in a headless environment: https://github.com/aeyoll/soulseek-cli#on-headless-linux
Can you give it a try? Thanks!

**Comment by iynere** [comment]
thanks, i'll try it!

**Comment by iynere** [comment]
oh, right, i remember this problem, i'm using Termux on Android & don't think I can install `gnome-keyring`, unless i can figure out how to do it manually... @aeyoll

**Comment by iynere** [comment]
@aeyoll i'm not using a headless environment, strictly speaking... i'm using Termux

**Comment by iynere** [comment]
@aeyoll I think you should find a different way to manage authentication, because honestly, Android usage is probably the best use case for a Soulseek CLI... There is no way to use Soulseek on mobile devices (since newalbum.club is gone), _unless_ we can get one running on Android via Termux

**Comment by aeyoll** [comment]
@iynere I released a new version where you can login using environment variables: https://github.com/aeyoll/soulseek-cli/#login. Tell me if it works out for you.
