### ISSUE TITLE
[Error: Cannot create an item in a locked collection]

### ISSUE THREAD

**Issue by invertedEcho** [aeyoll/soulseek-cli#37]
On logging in, I get

```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: Cannot create an item in a locked collection]

Node.js v17.8.0
```

This happens on master & develop branch.

**Comment by invertedEcho** [comment]
Workaround would be to use the environment vars login method, but still, a bug.

**Comment by aeyoll** [comment]
Hello @aznd,
Can you tell me more about your environment please? Looks like a keyring issue.

**Comment by invertedEcho** [comment]
Sorry, forgot about this.
Yeah, probably. I'm just running dwm with the help of startx.
